### ISSUE TITLE
コーディングスタイル

### ISSUE THREAD

**Issue by touyou** [YakinikuOishii/TMA#1]
https://github.com/YakinikuOishii/TMA/blob/62db1bb9cbfeb0f983c898d83101eac2e838b468/TMA/AddGoalViewController.swift#L26-L35

波括弧の前後は空白一個入れるようにする癖つけておきましょう。

**Comment by touyou** [comment]
@YakinikuOishii  カードにしたIssueはCloseするとDoneに自動で移動してくれたはずだからこっちからやると便利だよー

**Comment by YakinikuOishii** [comment]
> @YakinikuOishii カードにしたIssueはCloseするとDoneに自動で移動してくれたはずだからこっちからやると便利だよー

え、めっちゃ便利ですね！！！次からそうします！
